# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-28 23:14
from __future__ import unicode_literals

from django.db import migrations, models
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GraphVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_unixdatetimefield.fields.UnixDateTimeField()),
                ('committed_at', django_unixdatetimefield.fields.UnixDateTimeField()),
                ('temporal_graph_id', models.CharField(max_length=64, null=True)),
                ('version_id', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='graphversion',
            unique_together=set([('temporal_graph_id', 'version_id')]),
        ),
    ]
