# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-28 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_series_client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphversion',
            name='committed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='graphversion',
            name='temporal_graph_id',
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='graphversion',
            name='version_id',
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
    ]
