# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-29 00:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('time_series_client', '0002_auto_20171028_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEdgeWeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_unixdatetimefield.fields.UnixDateTimeField()),
                ('committed_at', django_unixdatetimefield.fields.UnixDateTimeField()),
                ('user_id', models.IntegerField()),
                ('edge_id', models.CharField(max_length=64)),
                ('weight_id', models.CharField(max_length=64)),
                ('weight', models.FloatField()),
                ('graph_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time_series_client.GraphVersion')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='useredgeweight',
            unique_together=set([('user_id', 'edge_id', 'weight_id')]),
        ),
    ]
