# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-29 02:08
from __future__ import unicode_literals

from django.db import migrations
import django.utils.timezone
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('time_series_client', '0003_auto_20171029_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphversion',
            name='committed_at',
            field=django_unixdatetimefield.fields.UnixDateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='graphversion',
            name='created_at',
            field=django_unixdatetimefield.fields.UnixDateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='useredgeweight',
            name='committed_at',
            field=django_unixdatetimefield.fields.UnixDateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='useredgeweight',
            name='created_at',
            field=django_unixdatetimefield.fields.UnixDateTimeField(default=django.utils.timezone.now),
        ),
    ]
