# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-30 01:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_series_client', '0006_auto_20171029_2339'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useredgeweight',
            unique_together=set([('graph_version', 'user_id', 'source_vertex_id', 'target_vertex_id', 'weight_id')]),
        ),
    ]
