# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-30 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_series_client', '0007_auto_20171030_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useredgeweight',
            name='weight',
            field=models.FloatField(null=True),
        ),
    ]
